# specify the name would change the prefix of the container name, volume name, network name etc.
name: key-value-store

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env.db-key-value
    environment:
      - MONGODB_HOST=db
      - PORT= 3000
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
    depends_on:
      - db
    networks:
      - key-value-net
  db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    ports:
      - 27017:27017
    env_file:
      - .env.db-root-creds
      - .env.db-key-value
    volumes:
      - type: bind   # this way is more explicit
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      - key-value-net

# specify network
networks:
  key-value-net:

# specify volumes
volumes:
  mongodb-data: