# This image is enough to run the backend of the key-value-app.
FROM node:22-alpine

WORKDIR /app

# copy package.json and package-lock.json to the working directory
# Before copy this file, the /app directory is empty. We only copy this package json file to setup the dependencies.
COPY package*.json .

# install dependencies
RUN npm ci

# copy all files and folders to the working directory (mainly to copy the remaining files and folders)
COPY . .

# Hot reloading for development
CMD ["npm", "run", "dev"]